[package]
name = "LunoaQuests"
version = "1.0.0"

[addresses]
LunoaQuests = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
